### PR TITLE
Update aminoacids.ff

### PR DESCRIPTION
**Pull request by fgrunewald**
remove redundant link in ff martini3001

### CODE REVIEW

**Comment by fgrunewald** [comment]
@pckroon what about this lint stuff?

**Comment by pckroon** [comment]
The lint is an issue. I would like to improve it, but I don't have the time. If you *do* have the time I would be very grateful. Otherwise I'm seriously considering running `black` to take care of it all.

**Comment by pckroon** [comment]
Or we stop running pylint. But that sounds wrong.

**Review by pckroon — APPROVED** [review]

**Comment by fgrunewald** [comment]
@pckroon I guess we keep it as implicit default then?

**Comment by pckroon** [comment]
I guess so. Does it mean issue #525 is invalid?

**Comment by fgrunewald** [comment]
@pckroon I the issue an discussion. If I understand the people involved correctly this is not the intended use-case for this link, but now it is.

**Pull request closed without merging**
