### PR TITLE
Log disulfide bridges

### PR DESCRIPTION
**Pull request by csbrasnett**
Small useful feature to write where disulfide bridges have actually been found as per #620. Can't see any effect on time. message might need some work.

### CODE REVIEW

**Review by pckroon — CHANGES_REQUESTED** [review]
I like the idea, but I think you can already achieve this by adding a `[ info ]` section to the link:
```
;; Cystein bridge
[ link ]
resname "CYS"
[ constraints ]
SC1 >SC1 1 0.24 {"comment": "Disulfide bridge"}
[ features ]
disulfide
[ info ]
Disulfide bridge found between residues {SC1['chain']}-{SC1['resname']}{SC1['resid']} and {>SC1['chain']}-{>SC1['resname']}{>SC1['resid']}
```
Note that this is an educated guess and YMMV

**Comment by csbrasnett** [comment]
Nice, that worked with a small adjustment thanks!

**Review by pckroon — COMMENTED** [review]
Awesome. I love preempting requests this way.
Also, could you add it to the other force fields as well?

**Review by pckroon — APPROVED** [review]
LGTM!

**Pull request merged**
