### PR TITLE
Update run_pylint.py

### PR DESCRIPTION
**Pull request by fgrunewald**
Fixes the broken pylint runner.

### CODE REVIEW

**Comment by fgrunewald** [comment]
This is a quite strange bug. One problem for sure is the usage of 'global_note' as dict key versus class attribute. For polyply that was enough to fix it. Now the exit code is also not 1 anymore but rather 28. As detailed here https://stackoverflow.com/questions/67061702/what-is-pylint-exit-code-28 this should have to do with formatting. However, after copying the pylintrc from polyply it still fails. I also cannot see an open issue that would directly apply to this. Again the fact that pylint works in polyply makes even more strange ...

**Comment by pckroon** [comment]
Is the run_pylint.py still needed? IIRC they added a --fail-under to pylint proper

**Comment by fgrunewald** [comment]
I guess the answer is no we don't need it, but the error we get is not related to that as far as I can tell.

**Comment by pckroon** [comment]
Removing the run_pylint.py reduces the complexity, so I'd say it's a good start. Beyond that I don't know.

**Comment by fgrunewald** [comment]
This PR becomes irrelevant with the update in #407.

**Pull request closed without merging**
