### PR TITLE
GO IDP bugfix

### PR DESCRIPTION
**Pull request by csbrasnett**
Need to add secstruc to the water bias application, otherwise can't apply across a whole protein (starting resid has to be > 1). this should fix that. And add preprint citation.

### CODE REVIEW

**Review by fgrunewald — CHANGES_REQUESTED** [review]
Needs at least one integration test in my opinion. 

@csbrasnett do you think the citation should also be added in the water bias processor?

**Comment by csbrasnett** [comment]
I'm not certain, but I think adding again there would be degenerate anyway? VirtualSiteCreator gets called both in the Go model and if `args.water_bias` is used, so I think just adding it there should be fine.

Happy to write an integration test. It strikes me this might be a good opportunity to deal with #585 at the same time, so I can do that as well?

**Comment by fgrunewald** [comment]
@csbrasnett I'd rather have 2 separate PRs, so that we can release this bug fix in near time

**Review by fgrunewald — CHANGES_REQUESTED** [review]
looks good but waiting for @csbrasnett to complete all changes

**Comment by csbrasnett** [comment]
This *should* bring things in line with polyply for generating topologies of idps. Maybe this is the right approach, maybe it isn't, but here's some kind of implementation either way. Happy to be advised whatever.

To do:

1) properly check against polyply
2) make some tests
3) maybe propagate secondary structure for automatic id/suggestions of IDRs?

**Pull request closed without merging**
