### PR TITLE
Add citation of M3 small molecules (address issue #468)

### LINKED ISSUE #468: Citations for Small Molecule DB missing
It appears we forgot to add citations for the parameters from the small molecule DB PR #456.

### PR DESCRIPTION
**Pull request by ricalessandri**
This should fix issue #468. #hacktoberfest

fixes #468

### CODE REVIEW

**Review by pckroon — CHANGES_REQUESTED** [review]
Could you move these files to the appropriate data folder? That will also make looking at the changes easier.

**Comment by ricalessandri** [comment]
Sorry, not sure how that happened. Fixed!

**Review by pckroon — APPROVED** [review]
LGTM, thanks!

Fixes #468

**Comment by ricalessandri** [comment]
Some checks seems to be hanging, let me know if there's anything I should do.

**Pull request merged**
